//
// Created by Azusa on 2022/4/25.
//

#ifndef DOREMICHORD_BACKEND_MODELREGISTER_H
#define DOREMICHORD_BACKEND_MODELREGISTER_H
#define TYPE_BASE_MODEL 0

#endif //DOREMICHORD_BACKEND_MODELREGISTER_H
